# Generated by Django 6.0.2 on 2026-02-26 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1)),
                ('age', models.IntegerField()),
                ('height', models.FloatField(help_text='Рост в см')),
                ('current_weight', models.FloatField(help_text='Текущий вес в кг')),
                ('target_weight', models.FloatField(help_text='Желаемый вес в кг')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Сидячий образ жизни'), ('light', 'Легкая активность'), ('moderate', 'Умеренная активность'), ('active', 'Высокая активность'), ('very_active', 'Очень высокая активность')], max_length=20)),
                ('goal', models.CharField(choices=[('lose', 'Похудение'), ('maintain', 'Поддержание веса'), ('gain', 'Набор массы')], max_length=10)),
                ('daily_calories', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
