services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: uvicorn wellness_backend.asgi:application --host 0.0.0.0 --port 8000 --workers 4
    env_file:
      - .env
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    build:
      context: ./deploy
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/app/staticfiles
      - media:/app/media
      - ./certbot_conf:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot
    depends_on:
      - web
      - frontend
    restart: always

  frontend:
    image: sofisofi01/aegle-frontend:latest
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot_conf:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done'"

volumes:
  postgres_data:
  staticfiles:
  media:
  # Убрали certbot_www и certbot_conf из именованных томов
