FROM nginx:alpine

RUN printf 'upstream django {\n    server web:8000;\n}\n\nserver {\n    listen 80;\n    server_name 72.56.6.10 zavyalova.h1n.ru;\n\n    client_max_body_size 10M;\n\n    location /static/ {\n        alias /app/staticfiles/;\n    }\n\n    location /media/ {\n        alias /app/media/;\n    }\n\n    location / {\n        proxy_pass http://django;\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n    }\n}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
