upstream web_backend {
    server web:8000;
}

server {
    listen 80;
    server_name 72.56.6.10 zavyalova.h1n.ru xn--80abcyabjk1czh.xn--p1ai;

    client_max_body_size 10M;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location /admin/ {
        proxy_pass http://web_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        # proxy_pass http://frontend:80;
        # proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
        return 200 "Backend is running. Frontend is coming soon...";
        add_header Content-Type text/plain;
    }
}
