upstream web_backend {
    server web:8000;
}

server {
    listen 80;
    server_name 72.56.6.10 zavyalova.h1n.ru;

    client_max_body_size 10M;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location / {
        resolver 127.0.0.11 valid=30s;
        set $backend_server web_backend;
        proxy_pass http://$backend_server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
